..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe bokehPass.frag -o bokehPassFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe swapchain.frag -o swapchainFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe finalPassShader.frag -o finalPassShaderFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe upscaleShader.frag -o upscaleShaderFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe blurShader.frag -o	blurShaderFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe quadRender.vert -o	quadRenderVERT.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe brightnessFilter.frag -o brightnessFilterFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe emissiveShader.frag -o	emissiveShaderFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe emissiveShader.vert -o	emissiveShaderVERT.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe particle.frag -o particleFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe particle.vert -o particleVERT.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe shadowPass.vert -o	shadowPassVERT.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe pointShadowPass.frag -o pointShadowPassFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe pointShadowPass.vert -o pointShadowPassVERT.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe pointShadowPass.geom -o pointShadowPassGEOM.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe PBRShader.vert -o PBRShaderVERT.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe PBRShader.frag -o PBRShaderFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe cubemap.frag -o cubemapFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe cubemap.vert -o cubemapVERT.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe Clouds.frag -o CloudsFRAG.spv
..\vendor\VULKAN\1.3.239.0\Bin\glslc.exe Clouds.vert -o CloudsVERT.spv
pause