..\vendor\VULKAN\1.3.211.0\bin\glslc.exe swapchain.frag -o swapchainFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe finalPassShader.frag -o finalPassShaderFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe upscaleShader.frag -o upscaleShaderFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe blurShader.frag -o blurShaderFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe QuadRender.vert -o quadRenderVert.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe BrightnessFilter.frag -o brightnessFilterShaderFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe emissiveShader.frag -o emissiveShaderFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe emissiveShader.vert -o emissiveShaderVERT.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe shaderTest.frag -o shaderTestFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe shaderTest.vert -o shaderTestVERT.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe particle.frag -o particleFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe particle.vert -o particleVERT.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe shadowPass.frag -o shadowPassFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe shadowPass.vert -o shadowPassVERT.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe PBRShader.vert -o PBRShaderVERT.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe PBRShader.frag -o PBRShaderFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe cubemap.frag -o cubemapFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe cubemap.vert -o cubemapVERT.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe lightSourceFrag.frag -o lightSourceFRAG.spv
..\vendor\VULKAN\1.3.211.0\bin\glslc.exe lightSourceVERT.vert -o lightSourceVERT.spv
pause